// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBooks.Models;

namespace MyBooks.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20201101175417_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyBooks.Models.BooksModel", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("authorBook")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("genreBook")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("nameBook")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("pagesBook")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.ToTable("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
